# Generated by Django 5.1.7 on 2025-05-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
    ]
