# Generated by Django 5.1.7 on 2025-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
