# Generated by Django 5.1.7 on 2025-05-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_wallet_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
