# Generated by Django 5.1.7 on 2025-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_coupon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
