# Generated by Django 5.1.7 on 2025-07-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_productvariant_final_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
