# Generated by Django 5.1.7 on 2025-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_discounted_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_amount',
            new_name='total_discount',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
