# Generated by Django 5.1.7 on 2025-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_discounted_amount_order_final_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
